kube version

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -235,23 +235,23 @@ check_prereqs() {
   # 7. enough space for the bootstrap on docker folder
   folder=`$docker_path info --format '{{.DockerRootDir}}'`
   safe_folder=${folder:-/var/lib/docker}
-  test=$(($(stat -f --format="%a*%S" $safe_folder)/1024**3 < 5))
-  if [[ $test -ne 0 ]] ; then
-    echo "You have less than 5GB of free space on the disk where $safe_folder is located. You will need more space to continue"
-    df -h $safe_folder
-    echo
-    if tty >/dev/null; then
-      read -p "Would you like to attempt to recover space by cleaning docker images and containers in the system?(y/N)" -n 1 -r
-      echo
-      if [[ $REPLY =~ ^[Yy]$ ]]
-      then
-        $docker_path container prune --force --filter until=1h >/dev/null
-        $docker_path image prune --all --force --filter until=1h >/dev/null
-        echo "If the cleanup was successful, you may try again now"
-      fi
-    fi
-    exit 1
-  fi
+  #test=$(($(stat -f --format="%a*%S" $safe_folder)/1024**3 < 5))
+  # if [[ $test -ne 0 ]] ; then
+  #   echo "You have less than 5GB of free space on the disk where $safe_folder is located. You will need more space to continue"
+  #   df -h $safe_folder
+  #   echo
+  #   if tty >/dev/null; then
+  #     read -p "Would you like to attempt to recover space by cleaning docker images and containers in the system?(y/N)" -n 1 -r
+  #     echo
+  #     if [[ $REPLY =~ ^[Yy]$ ]]
+  #     then
+  #       $docker_path container prune --force --filter until=1h >/dev/null
+  #       $docker_path image prune --all --force --filter until=1h >/dev/null
+  #       echo "If the cleanup was successful, you may try again now"
+  #     fi
+  #   fi
+  #   exit 1
+  # fi
 }
 
 
